#!/bin/sh
BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#7f64a8'
TEXT='#d2bee0'
WRONG='#39166d'
VERIFYING='#8f2be5'

i3lock \
	--insidever-color=$CLEAR     \
	--ringver-color=$VERIFYING   \
	\
	--insidewrong-color=$CLEAR   \
	--ringwrong-color=$WRONG     \
	\
	--inside-color=$BLANK        \
	--ring-color=$DEFAULT        \
	--line-color=$BLANK          \
	--separator-color=$DEFAULT   \
	\
	--verif-color=$TEXT          \
	--wrong-color=$TEXT          \
	--time-color=$TEXT           \
	--date-color=$TEXT           \
	--layout-color=$TEXT         \
	--keyhl-color=$WRONG         \
	--bshl-color=$WRONG          \
	\
	--screen 1                   \
	--blur 6                     \
	--clock                      \
	--indicator                  \
	--time-str="%H:%M:%S"        \
	--date-str="%A, %m %Y"       \
	--keylayout 1                \
